### ISSUE TITLE
Improve layout

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Tutorial#14]
- [ ] Better handling of rotation
- [ ] Add auto layout?

**Comment by 3lvis** [comment]
@vadymmarkov this is done now?

**Comment by vadymmarkov** [comment]
@3lvis I think yes.

**Comment by fmaylinch** [comment]
Sorry if this is not the place to ask this, and if my question was already resolved.

How can I use autolayout with this library? I see the examples and the doc are hardcoding the view frames, while the positioning is relative (with percentages). How can I combine these two different approaches?

What I've been doing is hardcoding the frames too, and calculating the percentage they represent relative to the view. That way I can combine those calculated percentages and the percentages that Position objects expect.

For example, I add an image with size 200x100. Then calculate the size percentage to the screen width and height. Then say I position this image at 0.6, 0.2. Now I can, for example, add another image aligned to the first one.

Any help will be appreciated. Thank you!
