### ISSUE TITLE
Is Tutorial a good name? It can do so much more.

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Tutorial#24]

**Comment by 3lvis** [comment]
Any examples?

**Comment by vadymmarkov** [comment]
That's a good point. Do you already have some ideas? :smile:

**Comment by zenangst** [comment]
- Book
- Story
- Magazine
- Guide
- Sheets
- Presenter
- Presentation
- Announcement

I think my favorite is Story, seeing as it uses Pages to present itself.

**Comment by vadymmarkov** [comment]
I can add one more - `Notes`.
But I think `Story` is the best one.

**Comment by 3lvis** [comment]
Pages could be better for this project, then we rename the other one.

**Comment by vadymmarkov** [comment]
My first association with Pages is Apple's word app. It our case we have something more like Keynote.

**Comment by 3lvis** [comment]
We went for Presentation.

**Comment by zenangst** [comment]
Thanks guys! You're the best :cake:
